In [ ]:
from statsmodels.stats.proportion import proportions_ztest
import numpy as np
significance = 0.05 #alpha value
successes = np.array([320, 300])
samples = np.array([400, 425])

In [ ]:
stat,p_value = proportions_ztest(count=successes,nobs=samples,alternative='two-sided')

In [ ]:
print('z_stat: %0.5f, p_value: %0.5f' % (stat, p_value))


z_stat: 3.12644, p_value: 0.00177
Reject the null hypothesis


In [ ]:
if p_value < significance:
  print ("Reject the null hypothesis")
else:
  print ("Accept the null hypothesis")

Reject the null hypothesis


In [ ]:
import scipy.stats as stats

In [ ]:
significance = 0.05
A = np.array([43, 53, 65, 49, 55, 60, 47, 50, 60, 55])
B = np.array([62, 43, 54, 67, 59, 45, 46, 63, 65, 45])

In [ ]:
stat, p_value = stats.ttest_ind(a = A, b = B, equal_var = True)

In [ ]:
print('t_stat: %0.5f, p_value: %0.4f' % (stat, p_value))
if p_value < significance:
  print ("Reject the null hypothesis")
else:
  print ("Accpet the null hypothesis")

t_stat: -0.32795, p_value: 0.7467
Accpet the null hypothesis


In [ ]:
import scipy.stats as stats

In [ ]:
significance = 0.05
A = np.array([43, 53, 65, 49, 55, 60, 147, 50, 60, 55])
B = np.array([62, 43, 54, 67, 59, 45, 46, 63, 65, 45])

In [ ]:
stat, p_value = stats.ttest_ind(A, B, equal_var = False)

In [ ]:
print('t_stat: %0.5f, p_value: %0.4f' % (stat, p_value))
if p_value < significance:
  print ("Reject the null hypothesis")
else:
  print ("Accpet the null hypothesis")

t_stat: 0.88668, p_value: 0.3946
Accpet the null hypothesis


In [ ]:
import scipy.stats as stats

In [ ]:
significance = 0.01
Pretest = np.array([60, 45, 80, 87, 79, 75, 60, 30, 45])
Posttest = np.array([75, 65, 90, 80, 89, 95, 85, 69, 40])

In [ ]:
stat, p_value = stats.ttest_rel(Pretest,Posttest)

In [ ]:
print('t_stat: %0.5f, p_value: %0.4f' % (stat, p_value))
if p_value < significance:
  print ("Reject the null hypothesis")
else:
  print ("Accpet the null hypothesis")

t_stat: -2.94514, p_value: 0.0186
Accpet the null hypothesis


In [ ]:
import pandas as pd
from scipy.stats import chi2_contingency

In [ ]:
df

Male  Female
Married    25      15
Single     35      25

In [ ]:
df = pd.DataFrame(index=["Married","Single"], data={'Male': [25, 35],'Female': [15,25]})

In [ ]:
chi2, p, dof, expected = chi2_contingency(df,correction=False)
print(f"chi2 statistic: {chi2:.5g}")
print(f"p-value: {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic: 0.17361
p-value: 0.67692
degrees of freedom: 1
expected frequencies:
[[24. 16.]
 [36. 24.]]


In [ ]:
row1 = [525,105,50]
row2 = [400,200,25]
row3 = [600,150,10]
data=[row1,row2,row3]
chi2, p, dof, expected = chi2_contingency(data)
print(f"chi2 statistic: {chi2:.5g}")
print(f"p-value: {p:.5g}")
print(f"degrees of freedom: {dof}")
print("expected frequencies:")
print(expected)

chi2 statistic: 87.136
p-value: 5.3406e-18
degrees of freedom: 4
expected frequencies:
[[502.17917676 149.83050847  27.99031477]
 [461.56174334 137.71186441  25.72639225]
 [561.2590799  167.45762712  31.28329298]]
